### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by poxin13** [BalliAsghar/find-2fa-codes#2]
Pretty new to raycast just trying to make a switch from Alfred. How do you install this extension? It doesn't seem to appear in the store.

I tried cloning the repo down and adding it as a script directory, didn't seem to work either.

**Comment by poxin13** [comment]
Okay, did it through Developer - Import Extension.

Thanks!

**Comment by youtextme** [comment]
Welcome — for Alfred → Raycast:

1. Keep Alfred on **Cmd-Space**; put free Raycast on **Option-Space** for a week.
2. This extension: open the repo → **Code** → install via Raycast developer import, or ask the author for a Store link. Store search only shows published extensions.
3. Port top clipboard/snippet habits first; leave the Alfred long-tail alone until Raycast feels native.

Free covers most launcher jobs. Pro is mainly sync / longer clipboard / AI — skip until a named lock shows up most workdays.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
